import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import tseslint from "typescript-eslint";
import reactPlugin from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import importPlugin from "eslint-plugin-import";
import perfectionist from "eslint-plugin-perfectionist";
import jsxA11y from "eslint-plugin-jsx-a11y";

export default defineConfig([
  /**
   * Base Next.js rules.
   *
   * This preset gives us:
   * - Next.js-specific rules
   * - React-related rules
   * - stricter checks related to performance and best practices
   *
   * It is a strong foundation for a modern Next.js app.
   */
  ...nextVitals,

  /**
   * Recommended TypeScript ESLint rules.
   *
   * These rules catch common TypeScript issues such as:
   * - unused variables
   * - unsafe patterns
   * - less maintainable constructs
   */
  ...tseslint.configs.recommended,

  /**
   * Stylistic TypeScript ESLint rules.
   *
   * These are not critical for app correctness,
   * but they help keep the codebase more consistent and readable.
   */
  ...tseslint.configs.stylistic,

  /**
   * Accessibility rules for JSX.
   *
   * This helps catch common accessibility problems like:
   * - missing labels
   * - invalid ARIA usage
   * - non-accessible interactive elements
   *
   * Very useful in projects with a lot of UI work.
   */
  jsxA11y.flatConfigs.recommended,

  /**
   * Core React rules.
   *
   * These rules help enforce good React practices
   * and catch common issues in JSX and component code.
   */
  reactPlugin.configs.flat.recommended,

  /**
   * React JSX runtime config.
   *
   * This supports the modern JSX transform,
   * so React does not need to be imported just for JSX.
   */
  reactPlugin.configs.flat["jsx-runtime"],

  /**
   * React Hooks rules.
   *
   * These are very important because they validate:
   * - correct hook usage order
   * - dependency arrays in useEffect and related hooks
   */
  reactHooks.configs.flat.recommended,

  {
    plugins: {
      import: importPlugin,
      perfectionist,
    },
    rules: {
      /**
       * Warn about console usage, but allow warn and error.
       *
       * This helps prevent accidental debug logs from staying in the code,
       * while still allowing intentional warning/error logging.
       */
      "no-console": ["warn", { allow: ["warn", "error"] }],

      /**
       * Warn when a debugger statement is left in the code.
       *
       * Useful because debugger is often forgotten after local debugging.
       */
      "no-debugger": "warn",

      /**
       * Enforce const when a variable is never reassigned.
       *
       * This improves readability and makes intent clearer.
       */
      "prefer-const": "error",

      /**
       * Warn about unused variables, arguments, and caught errors,
       * but ignore names starting with "_".
       *
       * This is useful when:
       * - an argument is required by a signature but intentionally unused
       * - you want to keep a placeholder for future use
       * - you intentionally ignore an error object
       */
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      /**
       * Prefer "type" imports for TypeScript-only imports.
       *
       * This makes it clearer which imports are used only for types
       * and helps keep the runtime import graph cleaner.
       */
      "@typescript-eslint/consistent-type-imports": [
        "warn",
        {
          prefer: "type-imports",
          fixStyle: "inline-type-imports",
        },
      ],

      /**
       * Disallow duplicate imports from the same module.
       *
       * Example:
       * import { a } from 'x';
       * import { b } from 'x';
       *
       * should be merged into a single import.
       */
      "import/no-duplicates": "error",

      /**
       * Keep imports sorted in a consistent way.
       *
       * Options:
       * - natural: human-friendly sorting, e.g. item2 before item10
       * - asc: ascending order
       * - newlinesBetween: always -> separate groups with empty lines
       *
       * This improves readability and keeps imports tidy.
       */
      "perfectionist/sort-imports": [
        "warn",
        {
          type: "natural",
          order: "asc",
          newlinesBetween: "always",
        },
      ],
    },
  },

  /**
   * Globally ignored files and folders.
   *
   * We ignore:
   * - .next -> generated by Next.js
   * - out / build -> build artifacts
   * - next-env.d.ts -> generated by Next.js
   * - Prisma generated client -> auto-generated code
   *
   * These files are not maintained by hand,
   * so linting them usually creates noise without value.
   */
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/shared/lib/db/generated/**",
  ]),
]);
